; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $2c, $87, $19, $87, $1b, $87, $18
@song0ref13:
	.byte $87
@song0ref14:
	.byte $14
@song0ref15:
	.byte $87, $16
@song0ref17:
	.byte $87, $18
@song0ref19:
	.byte $87, $16, $87, $14, $87, $16, $87, $18, $87, $16
	.byte $41, $09
	.word @song0ref13
	.byte $18, $87, $19, $87, $1b
	.byte $41, $09
	.word @song0ref17
	.byte $1b, $87, $1d, $87, $22, $87, $20, $87, $24, $87, $25, $87, $2e, $87, $33, $87, $2e, $87, $47, $29, $87, $27, $87, $2c
	.byte $87, $33, $87, $38, $87, $2c, $87, $19, $87, $12, $87, $14, $87, $19, $87, $1e, $87, $27, $87, $25, $87, $20, $87, $1d
	.byte $87, $1b, $87, $36, $87, $35, $87, $33, $87, $31, $87, $30, $87, $2e
@song0ref102:
	.byte $87, $2a, $87, $29
@song0ref106:
	.byte $87, $27, $87, $25, $87, $24, $87, $22, $87, $20, $87, $1e, $87, $1d, $87, $1b, $87, $47, $19, $87, $18, $87, $16, $87
	.byte $18, $87, $19, $87, $1b, $87, $1d, $87, $1e, $87, $20, $87, $22, $87, $24, $87, $25, $87, $27, $87, $29
	.byte $41, $15
	.word @song0ref102
	.byte $19, $87, $1b, $87, $1d, $87, $1b, $87, $19, $87, $14, $87, $0f, $87, $12, $87, $47
	.byte $41, $0e
	.word @song0ref14
	.byte $19, $87, $18, $87, $14, $87, $12, $87, $0e, $87, $0f, $87, $14, $87, $15, $87, $14, $87, $12, $87, $11, $87, $14, $87
	.byte $15, $87, $14, $87, $11, $87, $12, $87, $14, $87, $18, $87, $16, $87, $12
	.byte $41, $0b
	.word @song0ref15
	.byte $47, $19, $87, $1a, $87, $1b, $87, $1c, $87, $1d, $87, $1e, $87, $1f, $87, $20, $87, $21, $87, $22, $87, $23, $87, $24
	.byte $87, $25, $87, $26, $87, $27, $87, $28, $87, $29, $87, $28, $87, $27, $87, $26, $87, $25, $87, $24, $87, $23, $87, $22
	.byte $87, $21, $87, $20, $87, $1f, $87, $1e, $87, $1d, $87, $1c, $87, $1b, $87, $1a, $87, $47, $19, $87, $18, $87, $16, $87
	.byte $14, $87, $12, $87, $14
	.byte $41, $0a
	.word @song0ref19
@song0ref296:
	.byte $87, $14, $87, $12, $87, $14, $87, $16, $87, $14, $87, $16
	.byte $41, $09
	.word @song0ref296
	.byte $18, $87, $16, $87, $18
	.byte $41, $09
	.word @song0ref15
	.byte $18, $87, $16, $87, $14, $87, $12, $87, $47, $35, $87, $34, $87, $2e, $87, $2f, $87, $2b, $87, $2c, $87, $2a, $87, $27
	.byte $87, $27, $87, $27, $87, $27, $87, $26, $87, $1a, $87, $23, $87, $1c
@song0ref357:
	.byte $87, $26, $87, $1a, $87, $1c, $87, $21, $87, $26, $87, $1a, $87, $1c, $87, $21
	.byte $41, $0b
	.word @song0ref357
	.byte $21, $87, $1a, $87, $1c, $87, $19, $87, $47
@song0ref385:
	.byte $1a
@song0ref386:
	.byte $87, $19, $87, $1a, $87, $19, $87, $1a, $87, $19, $87
	.byte $41, $0a
	.word @song0ref385
	.byte $1a, $87, $26, $87, $1c, $87, $21, $87, $1a, $87, $1c, $87, $26, $87, $27, $87, $21, $87, $1c, $87, $26, $87, $23, $87
	.byte $27, $87, $29, $87, $30, $87, $25, $87, $26, $87, $12, $87, $13, $87, $14, $87, $15, $87, $47, $16, $87, $17, $87, $16
	.byte $87, $15, $87, $14
@song0ref452:
	.byte $87, $13
@song0ref454:
	.byte $87, $12, $87, $11
@song0ref458:
	.byte $87, $10, $87, $0f, $87, $10, $87, $11, $87, $12, $87, $14, $87, $15
	.byte $41, $0f
	.word @song0ref452
	.byte $13, $87, $12, $87, $10, $87, $11
	.byte $41, $0b
	.word @song0ref454
	.byte $0f, $87, $47, $0e, $87, $0f
	.byte $41, $09
	.word @song0ref458
	.byte $10, $87, $0e, $87, $0f, $87, $10, $87, $0f, $87, $10, $87, $0f, $87, $10, $87, $0f, $87, $10, $87, $28
	.byte $41, $0b
	.word @song0ref106
	.byte $1d, $87, $19, $87, $16, $87, $12, $87, $26, $87, $1a, $87, $1c, $87, $23, $87, $26, $87, $1a, $87, $47, $23, $87, $1c
	.byte $41, $0b
	.word @song0ref386
	.byte $1a, $87, $29, $87, $27, $87, $29, $87, $27, $87, $2a, $87, $2c, $87, $22, $87, $22, $87, $20, $87, $1e, $87, $29, $87
	.byte $2a, $87, $31, $87, $26, $87, $00, $e1, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref581:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $41, $09
	.word @song0ref581
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch4loop
